# Copyright 2014 William H. St. Clair
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: config | postgresql.conf
  template: dest={{ pg_data }}/postgresql.conf src=postgresql.conf.j2 owner=postgres group=postgres mode=0600 backup=yes

- name: config | pg_hba.conf
  template: dest={{ pg_data }}/pg_hba.conf src=pg_hba.conf.j2 owner=postgres group=postgres mode=0600 backup=yes

- name: config | write recovery.conf
  template: dest={{ pg_data }}/recovery.conf src=recovery.conf.j2 owner=postgres group=postgres mode=0600 backup=yes
  when: pg_recovery_conf_is_present

- name: config | remove recovery.conf
  file: path=recovery.conf state=absent
  when: not pg_recovery_conf_is_present
