# Copyright 2014 William H. St. Clair
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: create a new postgresql cluster
  hosts: localhost
  connection: local
  sudo: no
  gather_facts: false
  vars:
    key_name: "{{ ops_key_name }}"
    region: "{{ ops_aws_region }}"
    ami: ami-96a818fe
    instance_type: m3.medium

  tasks:
    - name: create database instances
      action: ec2
      args:
        assign_public_ip: yes
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: yes
        group_id: "{{ lookup('cloudformation', region + '/network/output/dbSg') }}"
        vpc_subnet_id: "{{ item.subnet_id }}"
        instance_tags:
          group: "{{ item.group }}"
      with_items:
        - subnet_id: "{{ lookup('cloudformation', region + '/network/output/subnet0') }}"
          group: pg_master
        - subnet_id: "{{ lookup('cloudformation', region + '/network/output/subnet1') }}"
          group: pg_replica